### ISSUE TITLE
Play ringtone already supported ;)

### ISSUE THREAD

**Issue by seblucas** [monster1025/aqara-mqtt#10]
Hi,

I don't know if you knew but you already support playing ringtone (I'm using it for a few months but never thought of writing about it). It work perfectly fine with : 

```
mosquitto_pub -h 192.168.0.108 -m '{"mid":10,"vol":5}' -t home/gateway/main/write
```

`mid` can be any of those : 
                                                0="police car 1",
                                                1="police car 2",
                                                2="accident",
                                                3="countdown", 
                                                4="ghost",
                                                5="sniper rifle",
                                                6="battle",
                                                7="air raid",
                                                8="bark", 
                                                10="doorbell",
                                                11="knock at a door",
                                                12="amuse",
                                                13="alarm clock",
                                                20="mimix",
                                                21="enthusuastic",
                                                22="guitar classic",
                                                23="ice world piano", 
                                                24="leisure time", 
                                                25="child hood", 
                                                26="morning stream liet", 
                                                27="music box", 
                                                28="orange", 
                                                29="thinker"
                                                10000="stop" <- Actually stop anything being played

and `vol` has to be between 0 and 99.

You can close it as it's not a real issue. It can be better integrated (like it was done with rgb ring) but it works.

**Comment by monster1025** [comment]
Yep, main feature of this gateway is support of all new xiaomi features 'out-of-the-box' because it is not necessary to know which data it will transfer to mqtt.
