### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by utya1988** [monster1025/aqara-mqtt#11]
Добрый день. Я так понимаю это у вас сборка под доскер, но всё написано на питон тоесть это всё можно запустить на устройстве с python? Какие при этом зависимости или какой питон нужен?

**Comment by monster1025** [comment]
Да, можно запустить на голом питоне. Но лучше в докере - переносимость лучше =) Все зависимости указаны в requirements.txt, питон 3.

**Comment by utya1988** [comment]
я хочу на openwrt поднять, тогда получиться чудесная штучка
