### ISSUE TITLE
docker problem

### ISSUE THREAD

**Issue by utya1988** [monster1025/aqara-mqtt#13]
Я наконец-то дорос до Docker. Но он у меня запущен на synology. Скачал ваш контейнер, но выдаёт ошибку при старте

FileNotFoundError: [Errno 2] No such file or directory: 'config/config.yaml'

я так понимаю он просто не видет папку конфига в которой прописаны mqtt сервер и датчики?

**Comment by monster1025** [comment]
Самое время переименовать config.yaml.sample в config.yaml и поменять там значения.

**Comment by utya1988** [comment]
да дописал app/config и заработало.

и ещё тогда вопрос три шлюза буде поддерживать?

**Comment by monster1025** [comment]
неа, поддержку нескольких шлюзов я так и не запилил.

**Comment by utya1988** [comment]
оо, ну это прям обидно(( а чё куда смотреть? вдруг у меня получиться

**Comment by monster1025** [comment]
скорее всего в сторону нескольких экземпляров XiaomiHub (если не будет конфликтов по портам) и обработки событий с них.

**Comment by utya1988** [comment]
разбираться здесь
https://github.com/monster1025/aqara-mqtt/blob/master/src/xiaomihub.py
?

**Comment by monster1025** [comment]
там похоже по всем файлам нужны будут правки: чтение конфига на несколько шлюзов, создание нескольких XiaomiHub, обработка событый с них и поллиг датчиков со всех шлюзов.

**Comment by utya1988** [comment]
ок, понял. спс. начну пока с одного

**Comment by utya1988** [comment]
стоп, а я же могу запустить столько контейнеров docker сколько у меня шлюзов, каждый контейнеров со своим конфигом?

**Comment by monster1025** [comment]
Просто так - нет, ибо UDP порт на физической машине один, и он "забит" в ответах от шлюза. Разве что, если каждый контейнер "забиндить" на отдельный IP (но тогда серваку придется как-то получить эти 3-ри IPшника и прокинуть каждый из них на контейнер).

**Comment by monster1025** [comment]
not an issue. closing.
