### ISSUE TITLE
Important question about Aqara devices

### ISSUE THREAD

**Issue by Barabba11** [monster1025/aqara-mqtt#22]
Hi mates, please apologize me if I create an issue, I need to comunicate with someone expert about Aqara and I don't know how I can find this people, please apologize again.
I've 3 main questions, I hope you can sove me them:
1) I've some led bulbs that are not compatible with wall switch without neutral, they don't let it activate and they "slightly vibrate". If I add a classiv bulb to them the problem disappears, it's pretty evident for me the reason but I want to know if this will be solved when I buy another wall switch with neutral, in that place luckly I can arrange the neutral wire.
2) Now I have all wall switches without neutral, but I don't have in any of them the long press function and the doble press, only on wireless switch. Are them present in wall switch with neutral?
3) I can't figure out how to send a voice command to Aqara hub, only Siri (and similars) can work? I've read it has inside a microphone, but what for? Spy us?
Thank you a lot!

**Comment by monster1025** [comment]
1. Just buy led capacitor from aliexpress and it will fix problem.
2. I do not know what exactly model do you jave - but usually no, thay didn't support dbl click when controlling bulb.
3. no, thay haven't. Use siri/alice/alexa, etc =)
